language: julia
os:
  - linux
  - osx
  - windows
arch:
  - x64
  # - x86
  - arm64
julia:
  - 1.3
  - nightly
env:
  matrix:
    - JULIA_NUM_THREADS=2
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
  exclude:
    # - os: osx
    #   arch: x86
    - os: osx
      arch: arm64
    - os: windows
      arch: arm64
    - julia: nightly
      arch: arm64
notifications:
  email: false
after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
